dados: dict[str, str] = {
    "quantos planetas tem o sistema solar?": "O Sistema Solar possui 8 planetas: Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno.",
    "qual é o maior planeta do sistema solar?": "Júpiter é o maior planeta do Sistema Solar.",
    "qual é o menor planeta do sistema solar?": "Mercúrio é o menor planeta do Sistema Solar.",
    "qual o planeta mais próximo do sol?": "Mercúrio é o planeta mais próximo do Sol.",
    "qual o planeta mais distante do sol?": "Netuno é o planeta mais distante do Sol.",
    "qual planeta é conhecido como o planeta vermelho?": "Marte é conhecido como o planeta vermelho, devido ao óxido de ferro em sua superfície.",
    "qual planeta tem os anéis mais visíveis?": "Saturno possui os anéis mais visíveis e impressionantes do Sistema Solar.",
    "quais planetas são gasosos?": "Os planetas gasosos são Júpiter, Saturno, Urano e Netuno.",
    "quais planetas são rochosos?": "Os planetas rochosos são Mercúrio, Vênus, Terra e Marte.",
    "qual é o planeta mais quente do sistema solar?": "Vênus é o planeta mais quente, devido ao seu intenso efeito estufa, mesmo não sendo o mais próximo do Sol.",
    "qual planeta gira mais rápido?": "Júpiter tem a rotação mais rápida, completando um dia em cerca de 10 horas.",
    "qual planeta tem a rotação mais lenta?": "Vênus possui a rotação mais lenta, levando cerca de 243 dias terrestres para girar uma vez em torno de seu eixo.",
    "qual planeta tem mais luas?": "Júpiter é o planeta com mais luas conhecidas, incluindo as famosas luas Galileanas: Io, Europa, Ganimedes e Calisto.",
    "quantas luas tem marte?": "Marte possui duas pequenas luas: Fobos e Deimos.",
    "quantas luas tem a terra?": "A Terra possui uma única lua natural, chamada simplesmente de Lua.",
    "qual é a maior lua do sistema solar?": "Ganimedes, uma das luas de Júpiter, é a maior lua do Sistema Solar.",
    "o que é a grande mancha vermelha de júpiter?": "A Grande Mancha Vermelha é uma tempestade gigante em Júpiter, maior que a Terra e ativa há mais de 300 anos.",
    "o que são os cinturões de asteroides?": "O cinturão de asteroides é uma região entre Marte e Júpiter onde orbitam muitos corpos rochosos.",
    "o que é a heliosfera?": "A heliosfera é uma bolha gigante de partículas carregadas criada pelo vento solar que envolve o Sistema Solar.",
    "o que é um planeta anão?": "Um planeta anão orbita o Sol, tem forma esférica, mas não domina sua órbita, como Plutão.",
    "plutão ainda é considerado planeta?": "Não. Desde 2006, Plutão é classificado como planeta anão pela União Astronômica Internacional.",
    "qual foi a primeira sonda a sair do sistema solar?": "A Voyager 1 foi a primeira sonda a alcançar o espaço interestelar, saindo da heliosfera do Sistema Solar.",
    "qual sonda explorou júpiter?": "A sonda Galileo explorou Júpiter entre 1995 e 2003.",
    "qual sonda explorou saturno?": "A sonda Cassini explorou Saturno e seus anéis entre 2004 e 2017.",
    "qual foi a primeira missão a pousar em marte?": "A Viking 1 foi a primeira missão a pousar com sucesso em Marte, em 1976.",
    "quanto tempo a terra leva para orbitar o sol?": "A Terra leva aproximadamente 365,25 dias para completar uma órbita ao redor do Sol.",
    "quanto tempo marte leva para orbitar o sol?": "Marte leva cerca de 687 dias terrestres para completar sua órbita ao redor do Sol.",
    "quanto tempo netuno leva para orbitar o sol?": "Netuno leva cerca de 165 anos terrestres para completar uma volta ao redor do Sol.",
    "qual é o diâmetro do sol?": "O diâmetro do Sol é aproximadamente 1,39 milhão de quilômetros.",
    "qual é a idade do sol?": "O Sol tem cerca de 4,6 bilhões de anos.",
    "qual é a classificação estelar do sol?": "O Sol é classificado como uma estrela anã amarela do tipo espectral G2V.",
    "como o sistema solar se formou?": "O Sistema Solar se formou há cerca de 4,6 bilhões de anos a partir de uma nuvem de gás e poeira interestelar que colapsou sob sua própria gravidade, formando o Sol no centro e os planetas ao redor.",
    "o que é o cinturão de kuiper?": "O cinturão de Kuiper é uma região além de Netuno, repleta de corpos gelados, incluindo Plutão e outros objetos transnetunianos.",
    "o que é a nuvem de oort?": "A nuvem de Oort é uma esfera teórica de corpos gelados que circunda o Sistema Solar, fonte de muitos cometas de longo período.",
    "o que são asteroides?": "Asteroides são corpos rochosos que orbitam o Sol, principalmente no cinturão de asteroides entre Marte e Júpiter.",
    "o que são meteoroides?": "Meteoroides são fragmentos menores de asteroides ou cometas que vagam pelo espaço.",
    "o que é um meteoro?": "Um meteoro é o fenômeno luminoso que ocorre quando um meteoroide entra na atmosfera da Terra e queima.",
    "o que é um meteorito?": "Um meteorito é o fragmento de meteoroide que sobrevive à passagem pela atmosfera e atinge a superfície da Terra.",
    "o que foi o big bang?": "O Big Bang foi o evento que marcou o início do universo há cerca de 13,8 bilhões de anos, a partir de uma expansão extremamente rápida de um ponto de densidade infinita.",
    "o sistema solar surgiu com o big bang?": "Não. O Big Bang deu origem ao universo, mas o Sistema Solar surgiu bilhões de anos depois, há cerca de 4,6 bilhões de anos."
}
